### ISSUE TITLE
London Transport causes crash on newest build

### ISSUE THREAD

**Issue by GasLoop** [grote/Liberario#65] opened 2015-03-17 00:11 UTC
I'm really looking forward to using Liberario in London, but apparently there is an issue with the link to the TfL API, causing Liberario to crash when opening Great Britain on the initial screen and when trying to enter information. On the earlier build, TfL is selectable, but every input prompts error message toasts, rendering the app useless.

Thank you for working on Liberario, @grote ! This app has a high potential, please keep it up. Oh, and add HVV (Hamburg) if possible, the API details can be requested via www.hvv.de. Cheers!

**Comment by grote** [comment] 2015-04-06 08:56
I can't reproduce the crash with current master HEAD anymore.

**Comment by grote** [comment] 2015-04-24 06:00
I'm closing this now. Please let me know if you still have the problem with today's 0.6 release.

**Closed by grote** 2015-04-24 06:00 UTC
Labels: bug
