### ISSUE TITLE
Problems with "DB" and "Offenbach"

### ISSUE THREAD

**Issue by dktzde** [grote/Liberario#76] opened 2015-05-08 06:49 UTC
When I search with "Deutsche Bahn" for a connection from any German railway Station (e.g. Nürnberg) to Offenbach (Offenbach Hbf, Offenbach Ost, an address in Offenbach) then Liberario crashes after the "search time" is over, at the moment, when it normally shows the connections. When I search for other connections without Offenbach there are no problems. When I use RailTeam (EU), then there are no problems. When I have a look to the "Deutsche Bahn" Website, I see no problems.

I got this bug with Version 0.5.3 and 0.6 from F-Droid repro and with version 0.6 from the Play Store (downloaded via 1Mobile Market)
I use CM 11 (Android 4.4.4) without any Play Services.

**Comment by grote** [comment] 2015-05-08 07:53
Ahhh, I could finally reproduce it. Deutsche Bahn is returning valid results without any connections probably due to the strike. This just never happened before and will be fixed in the next release.

**Comment by dktzde** [comment] 2015-05-08 09:53
Vielen Dank!

**Closed** 2015-05-09 00:49 UTC
Labels: bug, needs info
